In [14]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn import datasets
from sklearn import model_selection
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, cross_validate
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier


# Display plots inline and change plot resolution to retina
%matplotlib inline
%config InlineBackend.figure_format = 'retina'
# Set Seaborn aesthetic parameters to defaults
sns.set()
print('Setup Complete')

Setup Complete


In [15]:
def load_data():
    #load the dataset
    #return the dataset
    iris_data = datasets.load_iris()
    return iris_data

In [16]:
dataset = load_data()
load_data().feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [17]:
def dataset_to_pandas():
    #put the dataset into a pandas DF using the feature names as columnsç
    #rename the column name so the dont include the '(cm)'
    #add 2 columns one with the target and another with the target_names
    
    df = pd.DataFrame(dataset['data'], columns=dataset['feature_names'])
    df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width']
    df['target'] = dataset['target']
    df['class'] = dataset.target_names[dataset.target]

    #df['class'] = pd.Categorical.from_codes(dataset.target, dataset.target_names) #Make a Categorical type from codes and categories or dtype.
    #here the codes are the target values and the dtype will be target_names
    return df

In [18]:
df_iris = dataset_to_pandas()
df_iris

sepal length  sepal width  petal length  petal width  target      class
0             5.1          3.5           1.4          0.2       0     setosa
1             4.9          3.0           1.4          0.2       0     setosa
2             4.7          3.2           1.3          0.2       0     setosa
3             4.6          3.1           1.5          0.2       0     setosa
4             5.0          3.6           1.4          0.2       0     setosa
..            ...          ...           ...          ...     ...        ...
145           6.7          3.0           5.2          2.3       2  virginica
146           6.3          2.5           5.0          1.9       2  virginica
147           6.5          3.0           5.2          2.0       2  virginica
148           6.2          3.4           5.4          2.3       2  virginica
149           5.9          3.0           5.1          1.8       2  virginica

[150 rows x 6 columns]

In [19]:
def ohe():
    dummy = pd.get_dummies(df_iris, columns=["target"])
    return dummy
ohe()

sepal length  sepal width  petal length  petal width      class  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     target_0  target_1  target_2  
0           1         0         0  
1           1         0         0  
2           1         0         0  
3           1         0         0  
4           1         0         0  
..        ...       ...       ...  
145         0         0         1  
146         0         0         1  
147         0         0         1  
148         0         0         1  
149         0         0         1  

[150 rows x 8 columns]

In [20]:
def target_to_numpy():
    Y = df_iris.target.to_numpy()
    return Y
def data_to_numpy():
    X = df_iris[['sepal length','sepal width']].to_numpy() #only selects specified columns
    return X

Y = target_to_numpy()
X = data_to_numpy()


In [21]:
X = df_iris[['sepal length', 'sepal width']].values
print(X.shape)
X[:5]

(150, 2)


array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6]])

In [22]:
#Split the data into train and test
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.8, random_state = 42)

In [23]:
#normalize the dataset
#create and fit the scaler object on the training data

scaling = StandardScaler() 
X_train =  scaling.fit_transform(X_train)
X_test = scaling.fit_transform(X_test)

X_train[:5]

array([[-1.47393679,  1.20365799],
       [-0.13307079,  2.99237573],
       [ 1.08589829,  0.08570939],
       [-1.23014297,  0.75647855],
       [-1.7177306 ,  0.30929911]])

In [28]:
##deniz 
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

X = dataset.data
y = dataset.target

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 42)

model = DecisionTreeClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

print(cross_val_score(model, X_train, y_train, cv=3))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[0.95 0.9  0.95]
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy: 1.0


In [29]:
from sklearn.preprocessing import StandardScaler

X = dataset.data
y = dataset.target

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 42)

scaler = StandardScaler()  
a = scaler.fit(X_train)

X_train = a.transform(X_train)
X_test = scaler.transform(X_test)

model = DecisionTreeClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

print(cross_val_score(model, X_train, y_train, cv=3))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[0.925 0.925 0.95 ]
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy: 1.0


In [27]:
#Radom Forest Classifier
from sklearn.ensemble import RandomForestClassifier

X = dataset.data
y = dataset.target

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state = 13)

clf=RandomForestClassifier(n_estimators=100)

clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

[[ 9  0  0]
 [ 0  8  0]
 [ 0  1 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.89      1.00      0.94         8
           2       1.00      0.92      0.96        13

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

Accuracy: 0.9666666666666667
